/**
 * Verifies the storytelling problem pack against the interpreter and
 * emits an ADDITIVE SQL migration (sql/014_story_problems.sql).
 *
 * Run:  node_modules/.bin/tsx scripts/build-story-sql.ts
 *
 * The generated SQL inserts each problem only if its title does not
 * already exist, so it is safe to run on the live database.
 */
import { runGolfScript } from "../lib/golfscript";
import STORY from "./problems.story";
import * as fs from "fs";
import * as path from "path";

function normalize(s: string): string {
  return s.replace(/\r\n/g, "\n").replace(/\r/g, "\n").trim();
}

// Escape a string for a single-quoted SQL literal.
function q(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'";
}

// Build a Postgres text[] literal, e.g. {수학,구현}
function tagArray(tags: string[]): string {
  const inner = tags
    .map((t) => '"' + t.replace(/"/g, '\\"') + '"')
    .join(",");
  return q("{" + inner + "}");
}

const STEP_GROUP = "정보올림피아드 입문";

function main() {
  let failed = 0;
  const blocks: string[] = [];

  blocks.push(
    [
      "-- ============================================================",
      "--  Migration 014: storytelling problem pack (additive)",
      "--  Generated by scripts/build-story-sql.ts — do not hand-edit.",
      "--  Safe to re-run: each problem is inserted only if its title",
      "--  does not already exist.",
      "--  Run after 013_seed_tags.sql.",
      "-- ============================================================",
      "",
    ].join("\n"),
  );

  STORY.forEach((p, i) => {
    // Verify all cases.
    for (const c of p.cases) {
      const r = runGolfScript(p.solution, c.stdin, {
        timeoutMs: 3000,
        maxSteps: 5_000_000,
      });
      if (r.error || normalize(r.stdout) !== normalize(c.stdout)) {
        failed++;
        console.error(
          `FAIL [${p.title}] in=${JSON.stringify(c.stdin)} got=${JSON.stringify(
            normalize(r.stdout),
          )} exp=${JSON.stringify(normalize(c.stdout))} err=${r.error}`,
        );
      }
    }

    // Derive sample output from the sample input.
    const sr = runGolfScript(p.solution, p.sampleInput, {
      timeoutMs: 3000,
      maxSteps: 5_000_000,
    });
    const sampleOutput = normalize(sr.stdout);

    const order = i + 1;
    const caseValues = p.cases
      .map(
        (c) =>
          `    (new_id, ${q(c.stdin)}, ${q(c.stdout)}, ${c.hidden ? "true" : "false"})`,
      )
      .join(",\n");

    blocks.push(
      [
        `-- ${order}. ${p.title}`,
        `do $$`,
        `declare new_id bigint;`,
        `begin`,
        `  if not exists (select 1 from public.problems where title = ${q(p.title)}) then`,
        `    insert into public.problems`,
        `      (title, description, input_desc, output_desc, tier, source,`,
        `       sample_input, sample_output, step_group, step_order, tags)`,
        `    values (`,
        `      ${q(p.title)},`,
        `      ${q(p.description)},`,
        `      ${q(p.inputDesc)},`,
        `      ${q(p.outputDesc)},`,
        `      ${p.tier},`,
        `      ${q("자체 제작")},`,
        `      ${q(p.sampleInput)},`,
        `      ${q(sampleOutput)},`,
        `      ${q(STEP_GROUP)},`,
        `      ${order},`,
        `      ${tagArray(p.tags)}`,
        `    ) returning id into new_id;`,
        `    insert into public.test_cases (problem_id, stdin, stdout, is_hidden) values`,
        `${caseValues};`,
        `  end if;`,
        `end $$;`,
        "",
      ].join("\n"),
    );
  });

  if (failed > 0) {
    console.error(`\n${failed} case(s) failed. Aborting; no SQL written.`);
    process.exit(1);
  }

  blocks.push(
    [
      "-- ============================================================",
      "--  End of migration 014",
      "-- ============================================================",
      "",
    ].join("\n"),
  );

  const outPath = path.resolve(process.cwd(), "sql/014_story_problems.sql");
  fs.writeFileSync(outPath, blocks.join("\n"), "utf8");
  console.log(
    `OK: ${STORY.length} problems verified, ${STORY.reduce(
      (a, p) => a + p.cases.length,
      0,
    )} cases passed.`,
  );
  console.log(`Wrote ${outPath}`);
}

main();
