-- ============================================================
--  Migration 003: tiers + board
--  - Adds difficulty tier to problems (solved.ac style 0..30)
--  - Adds a community board (posts + comments)
--  Run this in the Supabase SQL Editor after 002_accounts.sql.
-- ============================================================

-- ------------------------------------------------------------
-- problems: difficulty tier (0 = Unrated, 1..30 = Bronze..Ruby)
-- ------------------------------------------------------------
alter table public.problems
  add column if not exists tier integer not null default 0;

-- ------------------------------------------------------------
-- posts (community board)
-- ------------------------------------------------------------
create table if not exists public.posts (
  id          bigint generated by default as identity primary key,
  user_id     uuid        not null references public.users(id) on delete cascade,
  title       text        not null,
  body        text        not null default '',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists posts_created_idx on public.posts(created_at desc);
create index if not exists posts_user_idx on public.posts(user_id);

-- ------------------------------------------------------------
-- comments
-- ------------------------------------------------------------
create table if not exists public.comments (
  id          bigint generated by default as identity primary key,
  post_id     bigint      not null references public.posts(id) on delete cascade,
  user_id     uuid        not null references public.users(id) on delete cascade,
  body        text        not null,
  created_at  timestamptz not null default now()
);

create index if not exists comments_post_idx on public.comments(post_id, created_at asc);

-- ------------------------------------------------------------
-- Row Level Security
-- ------------------------------------------------------------
alter table public.posts    enable row level security;
alter table public.comments enable row level security;

drop policy if exists "posts_public_read" on public.posts;
create policy "posts_public_read" on public.posts for select using (true);

drop policy if exists "comments_public_read" on public.comments;
create policy "comments_public_read" on public.comments for select using (true);

-- Writes go through the server (service_role), which bypasses RLS.
-- No INSERT/UPDATE/DELETE policies for anon = anon cannot write directly.

-- ------------------------------------------------------------
-- board view with author username joined
-- ------------------------------------------------------------
create or replace view public.board_posts as
select
  p.id,
  p.user_id,
  u.username as author,
  p.title,
  p.body,
  p.created_at,
  p.updated_at,
  (select count(*) from public.comments c where c.post_id = p.id) as comment_count
from public.posts p
join public.users u on u.id = p.user_id
order by p.created_at desc;

create or replace view public.board_comments as
select
  c.id,
  c.post_id,
  c.user_id,
  u.username as author,
  c.body,
  c.created_at
from public.comments c
join public.users u on u.id = c.user_id
order by c.created_at asc;

-- ============================================================
--  End of migration 003
-- ============================================================
