-- ============================================================
--  Migration 008: email verification + password reset
--  - users.email / email_verified
--  - auth_tokens: 이메일 인증 / 비밀번호 초기화 토큰 (해시 저장)
--  Run this in the Supabase SQL Editor after 007_images_notices.sql.
-- ============================================================

alter table public.users
  add column if not exists email text,
  add column if not exists email_verified boolean not null default false;

-- 이메일은 가입 시 소문자로 정규화하여 저장. 중복 방지(부분 유니크).
create unique index if not exists users_email_unique
  on public.users (lower(email))
  where email is not null;

-- 토큰 테이블: type = 'verify_email' | 'reset_password'
create table if not exists public.auth_tokens (
  id          bigint generated by default as identity primary key,
  user_id     uuid        not null references public.users(id) on delete cascade,
  token_hash  text        not null,
  type        text        not null check (type in ('verify_email', 'reset_password')),
  expires_at  timestamptz not null,
  used        boolean      not null default false,
  created_at  timestamptz not null default now()
);

create index if not exists auth_tokens_hash_idx on public.auth_tokens(token_hash);
create index if not exists auth_tokens_user_idx on public.auth_tokens(user_id);

-- auth_tokens 는 서버(service_role)만 접근. anon 정책 없음 = 접근 차단.
alter table public.auth_tokens enable row level security;

-- ============================================================
--  End of migration 008
-- ============================================================
