-- ============================================================
--  Migration 009: step groups as a managed table
--  Lets admins create/manage learning-path step groups in the DB
--  instead of the hardcoded scripts/problems.steps.ts list.
--  Run this in the Supabase SQL Editor after 008_email_auth.sql.
-- ============================================================

create table if not exists public.step_groups (
  id          bigint generated by default as identity primary key,
  name        text    not null unique,
  description text    not null default '',
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now()
);

create index if not exists step_groups_order_idx
  on public.step_groups(sort_order, id);

alter table public.step_groups enable row level security;

drop policy if exists "step_groups_public_read" on public.step_groups;
create policy "step_groups_public_read"
  on public.step_groups for select using (true);
-- Writes go through the server (service_role), which bypasses RLS.

-- Seed the existing groups in their current order.
insert into public.step_groups (name, description, sort_order) values
  ('입출력과 기본 연산', '스택에 올라온 입력을 다루고 사칙연산을 익힙니다.', 1),
  ('거듭제곱과 수의 성질', '제곱·세제곱·거듭제곱과 짝수/홀수/배수 판별.', 2),
  ('문자열 다루기', '문자열의 길이, 뒤집기, 정렬, 대소문자 변환.', 3),
  ('리스트와 집계', '여러 수의 합·곱·최댓값·최솟값·개수 구하기.', 4),
  ('반복과 수열', '범위 생성, 누적합, 나열과 패턴 출력.', 5),
  ('필터와 조건', '조건에 맞는 원소만 세고 거르기.', 6),
  ('자릿수와 진법', '각 자리 숫자를 분해하고 진법을 다룹니다.', 7),
  ('정렬과 선택', '정렬을 활용해 순위와 특정 값을 뽑아냅니다.', 8),
  ('정수론 입문', '약수, 소수, 완전수 같은 수의 성질을 탐구합니다.', 9),
  ('도전 과제', '고전 알고리즘과 정보올림피아드 유형에 도전하세요.', 10),
  ('문자열 응용', '단어 단위 처리와 텍스트 분석.', 11),
  ('정보올림피아드 입문', '이야기로 풀어보는 실전형 문제들. 수식을 코드로 옮겨 보세요.', 12)
on conflict (name) do nothing;

-- ============================================================
--  End of migration 009
-- ============================================================
