-- ============================================================
--  Migration 010: notifications
--  내 게시글에 댓글이 달리면 알림을 받는다.
--  Run this in the Supabase SQL Editor after 009_step_groups.sql.
-- ============================================================

create table if not exists public.notifications (
  id          bigint generated by default as identity primary key,
  user_id     uuid    not null references public.users(id) on delete cascade, -- 받는 사람
  actor       text    not null default '',   -- 행동한 사람 username
  type        text    not null,              -- 'comment'
  post_id     bigint  references public.posts(id) on delete cascade,
  message     text    not null default '',
  is_read     boolean not null default false,
  created_at  timestamptz not null default now()
);

create index if not exists notifications_user_idx
  on public.notifications(user_id, is_read, created_at desc);

-- 서버(service_role)만 접근. anon 정책 없음 = 직접 접근 차단.
alter table public.notifications enable row level security;

-- ============================================================
--  End of migration 010
-- ============================================================
