-- ============================================================
--  Migration 011: reports + difficulty votes (+ ban for rate-limit)
--  Run this in the Supabase SQL Editor after 010_notifications.sql.
-- ============================================================

-- 신고 (게시글/댓글)
create table if not exists public.reports (
  id           bigint generated by default as identity primary key,
  reporter_id  uuid    not null references public.users(id) on delete cascade,
  target_type  text    not null check (target_type in ('post', 'comment')),
  target_id    bigint  not null,
  reason       text    not null default '',
  status       text    not null default 'open' check (status in ('open', 'resolved', 'dismissed')),
  created_at   timestamptz not null default now()
);
create index if not exists reports_status_idx on public.reports(status, created_at desc);
alter table public.reports enable row level security;

-- 난이도 투표 (유저당 문제당 1표)
create table if not exists public.difficulty_votes (
  id          bigint generated by default as identity primary key,
  user_id     uuid    not null references public.users(id) on delete cascade,
  problem_id  bigint  not null references public.problems(id) on delete cascade,
  tier        integer not null check (tier between 1 and 30),
  created_at  timestamptz not null default now(),
  unique (user_id, problem_id)
);
create index if not exists difficulty_votes_problem_idx
  on public.difficulty_votes(problem_id);
alter table public.difficulty_votes enable row level security;

-- 제출 남용 정지: users 에 정지 만료 시각
alter table public.users
  add column if not exists banned_until timestamptz;

-- ============================================================
--  End of migration 011
-- ============================================================
