-- ============================================================
--  Migration 014: storytelling problem pack (additive)
--  Generated by scripts/build-story-sql.ts — do not hand-edit.
--  Safe to re-run: each problem is inserted only if its title
--  does not already exist.
--  Run after 013_seed_tags.sql.
-- ============================================================

-- 1. 달콤상점의 거스름돈
do $$
declare new_id bigint;
begin
  if not exists (select 1 from public.problems where title = '달콤상점의 거스름돈') then
    insert into public.problems
      (title, description, input_desc, output_desc, tier, source,
       sample_input, sample_output, step_group, step_order, tags)
    values (
      '달콤상점의 거스름돈',
      '달콤상점에 들른 소민이는 사탕을 한 봉지 샀습니다. 지갑에서 낸 돈과 사탕의 가격이 주어질 때, 점원이 돌려줘야 할 거스름돈을 계산해 주세요. 소민이는 항상 가격보다 크거나 같은 금액을 냅니다.',
      '공백으로 구분된 두 정수 ''낸 돈''과 ''가격''. (낸 돈 ≥ 가격)',
      '거스름돈, 즉 낸 돈에서 가격을 뺀 값.',
      3,
      '자체 제작',
      '5000 3200',
      '1800',
      '정보올림피아드 입문',
      1,
      '{"사칙연산","구현"}'
    ) returning id into new_id;
    insert into public.test_cases (problem_id, stdin, stdout, is_hidden) values
    (new_id, '5000 3200', '1800', false),
    (new_id, '10000 10000', '0', false),
    (new_id, '7000 2500', '4500', true),
    (new_id, '1000000 1', '999999', true);
  end if;
end $$;

-- 2. 피자 파티에 필요한 판 수
do $$
declare new_id bigint;
begin
  if not exists (select 1 from public.problems where title = '피자 파티에 필요한 판 수') then
    insert into public.problems
      (title, description, input_desc, output_desc, tier, source,
       sample_input, sample_output, step_group, step_order, tags)
    values (
      '피자 파티에 필요한 판 수',
      '동아리 회식에서 피자를 시키려 합니다. 사람 수와 피자 한 판의 조각 수가 주어집니다. 모든 사람이 적어도 한 조각씩 먹으려면 최소 몇 판을 시켜야 할까요? (한 사람당 한 조각으로 충분하다고 가정합니다.)',
      '공백으로 구분된 두 정수 ''사람 수 n''과 ''한 판의 조각 수 k''. (k ≥ 1)',
      '필요한 최소 피자 판 수, 즉 n을 k로 나눈 값의 올림.',
      9,
      '자체 제작',
      '10 4',
      '3',
      '정보올림피아드 입문',
      2,
      '{"수학","구현"}'
    ) returning id into new_id;
    insert into public.test_cases (problem_id, stdin, stdout, is_hidden) values
    (new_id, '10 4', '3', false),
    (new_id, '8 4', '2', false),
    (new_id, '1 8', '1', false),
    (new_id, '100 7', '15', true),
    (new_id, '21 3', '7', true);
  end if;
end $$;

-- 3. 텃밭 울타리 두르기
do $$
declare new_id bigint;
begin
  if not exists (select 1 from public.problems where title = '텃밭 울타리 두르기') then
    insert into public.problems
      (title, description, input_desc, output_desc, tier, source,
       sample_input, sample_output, step_group, step_order, tags)
    values (
      '텃밭 울타리 두르기',
      '할머니가 직사각형 모양의 텃밭 둘레에 울타리를 치려고 합니다. 텃밭의 가로와 세로 길이가 주어질 때, 울타리의 전체 길이(직사각형의 둘레)를 구해 주세요.',
      '공백으로 구분된 두 정수 ''가로''와 ''세로''.',
      '직사각형의 둘레, 즉 (가로 + 세로) × 2.',
      5,
      '자체 제작',
      '3 4',
      '14',
      '정보올림피아드 입문',
      3,
      '{"기하","수학"}'
    ) returning id into new_id;
    insert into public.test_cases (problem_id, stdin, stdout, is_hidden) values
    (new_id, '3 4', '14', false),
    (new_id, '1 1', '4', false),
    (new_id, '10 20', '60', true),
    (new_id, '100 1', '202', true);
  end if;
end $$;

-- 4. 보물섬까지의 거리
do $$
declare new_id bigint;
begin
  if not exists (select 1 from public.problems where title = '보물섬까지의 거리') then
    insert into public.problems
      (title, description, input_desc, output_desc, tier, source,
       sample_input, sample_output, step_group, step_order, tags)
    values (
      '보물섬까지의 거리',
      '해적 선장이 현재 위치 (x1, y1)에서 보물이 묻힌 지점 (x2, y2)까지의 거리를 재려 합니다. 제곱근은 배에서 계산하기 번거로우니, 두 점 사이 거리의 ''제곱'' 값만 구해 주세요.',
      '공백으로 구분된 네 정수 x1 y1 x2 y2.',
      '두 점 사이 거리의 제곱, 즉 (x2-x1)² + (y2-y1)².',
      10,
      '자체 제작',
      '0 0 3 4',
      '25',
      '정보올림피아드 입문',
      4,
      '{"기하","수학"}'
    ) returning id into new_id;
    insert into public.test_cases (problem_id, stdin, stdout, is_hidden) values
    (new_id, '0 0 3 4', '25', false),
    (new_id, '1 1 4 5', '25', false),
    (new_id, '2 2 2 2', '0', true),
    (new_id, '0 0 5 12', '169', true);
  end if;
end $$;

-- 5. 윤년의 비밀
do $$
declare new_id bigint;
begin
  if not exists (select 1 from public.problems where title = '윤년의 비밀') then
    insert into public.problems
      (title, description, input_desc, output_desc, tier, source,
       sample_input, sample_output, step_group, step_order, tags)
    values (
      '윤년의 비밀',
      '달력을 만드는 시계공이 어떤 해가 윤년인지 알아야 합니다. 어떤 연도가 윤년이려면 4의 배수이면서 100의 배수가 아니거나, 또는 400의 배수여야 합니다. 주어진 연도가 윤년이면 1을, 아니면 0을 출력해 주세요.',
      '한 개의 정수 ''연도 y''.',
      '윤년이면 1, 아니면 0.',
      9,
      '자체 제작',
      '2024',
      '1',
      '정보올림피아드 입문',
      5,
      '{"구현","수학"}'
    ) returning id into new_id;
    insert into public.test_cases (problem_id, stdin, stdout, is_hidden) values
    (new_id, '2024', '1', false),
    (new_id, '2023', '0', false),
    (new_id, '2000', '1', false),
    (new_id, '1900', '0', true),
    (new_id, '2400', '1', true),
    (new_id, '2100', '0', true);
  end if;
end $$;

-- 6. 합격자 발표
do $$
declare new_id bigint;
begin
  if not exists (select 1 from public.problems where title = '합격자 발표') then
    insert into public.problems
      (title, description, input_desc, output_desc, tier, source,
       sample_input, sample_output, step_group, step_order, tags)
    values (
      '합격자 발표',
      '코딩 시험의 합격 기준은 60점입니다. 60점 이상이면 합격입니다. 한 학생의 점수가 주어질 때, 합격이면 1을, 불합격이면 0을 출력해 주세요.',
      '한 개의 정수 ''점수'' (0 이상 100 이하).',
      '60점 이상이면 1, 아니면 0.',
      7,
      '자체 제작',
      '60',
      '1',
      '정보올림피아드 입문',
      6,
      '{"구현"}'
    ) returning id into new_id;
    insert into public.test_cases (problem_id, stdin, stdout, is_hidden) values
    (new_id, '60', '1', false),
    (new_id, '59', '0', false),
    (new_id, '100', '1', false),
    (new_id, '0', '0', true),
    (new_id, '61', '1', true);
  end if;
end $$;

-- 7. 출석 점수 계산기
do $$
declare new_id bigint;
begin
  if not exists (select 1 from public.problems where title = '출석 점수 계산기') then
    insert into public.problems
      (title, description, input_desc, output_desc, tier, source,
       sample_input, sample_output, step_group, step_order, tags)
    values (
      '출석 점수 계산기',
      '어느 강좌의 최종 점수는 ''출석 점수 × 2 + 과제 점수''로 정해집니다. 한 수강생의 출석 점수와 과제 점수가 순서대로 주어질 때 최종 점수를 구해 주세요.',
      '공백으로 구분된 두 정수 ''출석 점수 a''와 ''과제 점수 b''.',
      '최종 점수, 즉 a × 2 + b.',
      8,
      '자체 제작',
      '30 25',
      '85',
      '정보올림피아드 입문',
      7,
      '{"사칙연산","구현"}'
    ) returning id into new_id;
    insert into public.test_cases (problem_id, stdin, stdout, is_hidden) values
    (new_id, '30 25', '85', false),
    (new_id, '3 5', '11', false),
    (new_id, '50 0', '100', true),
    (new_id, '0 40', '40', true);
  end if;
end $$;

-- 8. 반 평균 점수
do $$
declare new_id bigint;
begin
  if not exists (select 1 from public.problems where title = '반 평균 점수') then
    insert into public.problems
      (title, description, input_desc, output_desc, tier, source,
       sample_input, sample_output, step_group, step_order, tags)
    values (
      '반 평균 점수',
      '선생님이 반 학생들의 시험 점수를 모아 평균을 내려 합니다. 점수들이 공백으로 구분되어 주어질 때, 점수의 평균을 정수로(소수점 이하 버림) 출력해 주세요.',
      '공백으로 구분된 한 개 이상의 정수 점수.',
      '점수들의 평균(내림).',
      10,
      '자체 제작',
      '80 90 100',
      '90',
      '정보올림피아드 입문',
      8,
      '{"배열","수학"}'
    ) returning id into new_id;
    insert into public.test_cases (problem_id, stdin, stdout, is_hidden) values
    (new_id, '80 90 100', '90', false),
    (new_id, '1 2 3 4', '2', false),
    (new_id, '100', '100', true),
    (new_id, '70 70 70 70', '70', true),
    (new_id, '55 90', '72', true);
  end if;
end $$;

-- 9. 일교차 구하기
do $$
declare new_id bigint;
begin
  if not exists (select 1 from public.problems where title = '일교차 구하기') then
    insert into public.problems
      (title, description, input_desc, output_desc, tier, source,
       sample_input, sample_output, step_group, step_order, tags)
    values (
      '일교차 구하기',
      '기상 관측소에서 하루 동안 여러 번 기온을 쟀습니다. 측정한 기온들이 주어질 때, 가장 높은 기온과 가장 낮은 기온의 차이(일교차)를 구해 주세요.',
      '공백으로 구분된 한 개 이상의 정수 기온.',
      '최고 기온에서 최저 기온을 뺀 값.',
      10,
      '자체 제작',
      '3 1 4 1 5',
      '4',
      '정보올림피아드 입문',
      9,
      '{"배열","정렬"}'
    ) returning id into new_id;
    insert into public.test_cases (problem_id, stdin, stdout, is_hidden) values
    (new_id, '3 1 4 1 5', '4', false),
    (new_id, '10 10', '0', false),
    (new_id, '5 9', '4', false),
    (new_id, '-3 0 7', '10', true),
    (new_id, '20', '0', true);
  end if;
end $$;

-- 10. 라면 타이머
do $$
declare new_id bigint;
begin
  if not exists (select 1 from public.problems where title = '라면 타이머') then
    insert into public.problems
      (title, description, input_desc, output_desc, tier, source,
       sample_input, sample_output, step_group, step_order, tags)
    values (
      '라면 타이머',
      '주방의 타이머는 남은 시간을 초 단위로만 보여 줍니다. 보기 편하도록 이를 ''분''과 ''초''로 바꿔 주세요. 예를 들어 125초는 2분 5초입니다.',
      '한 개의 정수 ''전체 초''.',
      '''분''과 ''초''를 공백으로 구분해 출력. (분 = 전체초 / 60, 초 = 전체초 % 60)',
      11,
      '자체 제작',
      '125',
      '2 5',
      '정보올림피아드 입문',
      10,
      '{"수학","구현"}'
    ) returning id into new_id;
    insert into public.test_cases (problem_id, stdin, stdout, is_hidden) values
    (new_id, '125', '2 5', false),
    (new_id, '60', '1 0', false),
    (new_id, '59', '0 59', false),
    (new_id, '3661', '61 1', true),
    (new_id, '0', '0 0', true);
  end if;
end $$;

-- 11. 로켓 발사 카운트다운
do $$
declare new_id bigint;
begin
  if not exists (select 1 from public.problems where title = '로켓 발사 카운트다운') then
    insert into public.problems
      (title, description, input_desc, output_desc, tier, source,
       sample_input, sample_output, step_group, step_order, tags)
    values (
      '로켓 발사 카운트다운',
      '우주센터에서 로켓 발사를 앞두고 카운트다운을 외칩니다. 시작 숫자 n이 주어지면 n부터 1까지 거꾸로 세어 한 줄에 공백으로 구분해 출력해 주세요.',
      '한 개의 정수 n. (n ≥ 1)',
      'n, n-1, …, 1을 공백으로 구분한 한 줄.',
      8,
      '자체 제작',
      '5',
      '5 4 3 2 1',
      '정보올림피아드 입문',
      11,
      '{"배열","구현"}'
    ) returning id into new_id;
    insert into public.test_cases (problem_id, stdin, stdout, is_hidden) values
    (new_id, '5', '5 4 3 2 1', false),
    (new_id, '3', '3 2 1', false),
    (new_id, '1', '1', false),
    (new_id, '10', '10 9 8 7 6 5 4 3 2 1', true);
  end if;
end $$;

-- 12. 용돈 모으기 대작전
do $$
declare new_id bigint;
begin
  if not exists (select 1 from public.problems where title = '용돈 모으기 대작전') then
    insert into public.problems
      (title, description, input_desc, output_desc, tier, source,
       sample_input, sample_output, step_group, step_order, tags)
    values (
      '용돈 모으기 대작전',
      '지호는 매주 같은 금액의 용돈을 받아 한 푼도 쓰지 않고 모으기로 했습니다. 한 주에 받는 용돈과 모으는 주 수가 주어질 때, 지호가 모으게 될 총 금액을 구해 주세요.',
      '공백으로 구분된 두 정수 ''주당 용돈''과 ''주 수''.',
      '모은 총 금액, 즉 두 수의 곱.',
      4,
      '자체 제작',
      '5000 10',
      '50000',
      '정보올림피아드 입문',
      12,
      '{"사칙연산"}'
    ) returning id into new_id;
    insert into public.test_cases (problem_id, stdin, stdout, is_hidden) values
    (new_id, '5000 10', '50000', false),
    (new_id, '3000 4', '12000', false),
    (new_id, '1 1', '1', true),
    (new_id, '12000 52', '624000', true);
  end if;
end $$;

-- ============================================================
--  End of migration 014
-- ============================================================
