-- ============================================================
--  Migration 015: admin audit log (monitoring)
--  Records sensitive admin actions such as viewing a user's
--  submission code, so admin access is traceable.
--  Run in the Supabase SQL Editor after 014_story_problems.sql.
-- ============================================================

create table if not exists public.admin_audit_log (
  id          bigint generated by default as identity primary key,
  admin_id    uuid    not null references public.users(id) on delete cascade,
  action      text    not null,            -- e.g. 'view_user_submissions'
  target_type text    not null default '', -- 'user' | 'submission' | ...
  target_id   text    not null default '', -- id of the affected entity
  detail      text    not null default '', -- free-form note
  created_at  timestamptz not null default now()
);

create index if not exists admin_audit_log_created_idx
  on public.admin_audit_log(created_at desc);
create index if not exists admin_audit_log_admin_idx
  on public.admin_audit_log(admin_id, created_at desc);

alter table public.admin_audit_log enable row level security;
-- Writes/reads go through the server (service_role), which bypasses RLS.

-- ============================================================
--  End of migration 015
-- ============================================================
